#버전을 정의해줌
version: 2.1
#이 항목 밑에 실행하려는 서비스들을 정의합니다.
#서비스란, 앱 컨테이너나 postgres 컨테이너 각각의 묶음입니다.
services:
  HOMEWROK2020:
    build: ./
    ports:
      - "8080:80"

    environment:
      - FLASK_APP=app/homework2.py
      - FLASK_DEBUG=1
      - "RUN=flask run --host=0.0.0.0 --port=80"
db:
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_DATABASE: "database2"
    # So you don't have to use root, but you can if you like
    MYSQL_USER: "admin"
    # You can use whatever password you like
    MYSQL_PASSWORD: "swaawogus55"
    # Password for root access
    MYSQL_ROOT_PASSWORD: "swaawogus55"
  ports:
    # <Port exposed> : < MySQL Port running inside container>
    - "3306:3306"
  expose:
    # Opens port 3306 on the container
    - "3306"
    # Where our data will be persisted
  volumes:
    - my-db:/var/lib/mysql
